---
- hosts: kube-master[0]

  tasks:
    - name: Checkout certificate
      fetch:
        src: /etc/kubernetes/ssl/apiserver.pem
        dest: /buddy/kubernetes/kubectl/certs/
        fail_on_missing: yes
        flat: yes

    - name: Checkout certificate
      fetch:
        src: /etc/kubernetes/ssl/apiserver-key.pem
        dest: /buddy/kubernetes/kubectl/certs/
        fail_on_missing: yes
        flat: yes
