---
- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: python

  tasks:       
    - name: Delete the cluster
      os_server:
        cloud: "{{cloud_env}}"
        name: "{{hostvars[item]['inventory_hostname']}}" 
        state: absent
      with_items: "{{groups['all']}}"
      when:
        - "\"{{hostvars[item]['inventory_hostname']}}\" != 'localhost'"
