---
- hosts: blue

  tasks:
    - name: Bootstrap the cluster
      docker_container:
        name: kargo
        image: rods/kargo
        command: kargo openstack -y --masters 1 --nodes 2 -p /root/repo/kargo --noclone
        state: started
        volumes:
          - /home/ubuntu/kargo/conf:/etc/kargo:rw
          - /home/ubuntu/kargo/ssh:/root/.ssh:rw
          - /home/ubuntu/kargo/repo:/root/repo:rw
        detach: False
