---
- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: python

  tasks:       
    - name: Delete the cluster
      os_server:
        cloud: "{{cloud_env}}"
        name: "{{hostvars[item]['inventory_hostname']}}" 
        state: absent
      with_items: "{{groups['all_nodes']}}"

    - name: Delete the ports
      os_port:
        cloud: "{{cloud_env}}"
        state: absent
        name: "{{hostvars[item]['inventory_hostname']}}" 
      with_items: "{{groups['all_nodes']}}"
