---
- name: Nuke the openstack cluster
  hosts: localhost

  tasks:
  - name: Get nodes list
    os_server_facts:
      server: "k8s-*"

  - name: Delete the nodes
    os_server:
      name: "{{item.name}}"
      state: absent
    with_items:
      - "{{openstack_servers}}"

  - name: Get ports list
    os_port_facts:
      port: "k8s-*"

  - name: Delete the ports
    os_port:
      state: absent
      name: "{{item.name}}" 
    with_items:
      - "{{openstack_ports}}"
