---
- hosts: localhost
  connection: local

  tasks:       
    - name: Create ports for the kube masters
      os_port:
        state: present
        name: "{{item}}" 
        network: "{{net}}"
      with_sequence: count={{masters_num}} format=k8s-master-%d

    - name: Boot kube masters
      os_server:
        name: "{{item}}" 
        state: present
        nics:
          - port-name: "{{ item }}" 
        image: "{{image}}"
        flavor: "{{masters_flavor}}"
        key_name: "{{key_name}}"
        security_groups: "{{security_groups}}"
        meta:
          group: kube-master
      with_sequence: count={{masters_num}} format=k8s-master-%d

    - name: Create ports for the kube nodes
      os_port:
        state: present
        name: "{{item}}" 
        network: "{{net}}"
      with_sequence: count={{nodes_num}} format=k8s-node-%d

    - name: Boot kube nodes
      os_server:
        name: "{{item}}" 
        state: present
        nics:
          - port-name: "{{item}}" 
        image: "{{image}}"
        flavor: "{{nodes_flavor}}"
        key_name: "{{key_name}}"
        security_groups: "{{security_groups}}"
        meta:
          groups: kube-node,etcd
      with_sequence: count={{nodes_num}} format=k8s-node-%d
