---
- hosts: localhost
  connection: local

  tasks:       
    - name: Create ports for the kube masters
      os_port:
        state: present
        name: "{{item}}" 
        network: "{{net}}"
      with_sequence: count={{masters_num}} format={{prefix}}-master-%d

    - name: Boot kube masters
      os_server:
        name: "{{item}}" 
        state: present
        nics:
          - port-name: "{{ item }}" 
        image: "{{image}}"
        flavor: "{{masters_flavor}}"
        key_name: "{{key_name}}"
        security_groups: "{{security_groups}}"
        meta:
          group: kube-master
        userdata: |
          #cloud-config
          hostname: "{{item}}"
          manage_etc_hosts: true
      register: kube_masters
      with_sequence: count={{masters_num}} format={{prefix}}-master-%d

    - add_host: name={{item.server.name}}
                groups=created_nodes
                ansible_user=ubuntu
                ansible_host={{item.server.public_v4}}
      with_items: "{{kube_masters.results}}"

    - name: Create ports for the kube nodes
      os_port:
        state: present
        name: "{{item}}" 
        network: "{{net}}"
      with_sequence: count={{nodes_num}} format={{prefix}}-node-%d

    - name: Boot kube nodes
      os_server:
        name: "{{item}}" 
        state: present
        nics:
          - port-name: "{{item}}" 
        image: "{{image}}"
        flavor: "{{nodes_flavor}}"
        key_name: "{{key_name}}"
        security_groups: "{{security_groups}}"
        meta:
          groups: kube-node,etcd
      register: kube_nodes
      with_sequence: count={{nodes_num}} format={{prefix}}-node-%d

    - add_host: name={{item.server.name}}
                groups=created_nodes
                ansible_host={{item.server.public_v4}}
      with_items: "{{kube_nodes.results}}"

- name: Configure nodes
  hosts: created_nodes
  become: yes
  become_method: sudo
  gather_facts: false

  tasks:
    - name: "Wait for SSH banners"
      local_action: wait_for port=22 host="{{inventory_hostname}}" search_regex=OpenSSH delay=5
